---
- name: get grafana version
  uri:
    url: "{{ grafana_protocol }}://{{ grafana_http_addr if grafana_protocol == 'http' else grafana_https_domain }}:{{ grafana_http_port if grafana_protocol == 'http' else '443' }}/api/health"
    return_content: yes
    timeout: 400
    validate_certs: "{{ validate_certs | default('yes') }}"
  register: grafana
  tags: test

- name: show versions
  debug: msg="current vesrion {{ grafana.json.version }}, expected version {{ grafana_install_version }}"
  tags: test

- fail: msg="version check failed"
  when: grafana.json.version is version(grafana_install_version, '!=')
  tags: test
